image: python:3.11

stages:
  - setup
  - run_app
  - push_output

setup:
  stage: setup
  script:
    - python -m venv myenv
    - source myenv/bin/activate
    - python -m ensurepip --default-pip
    - pip install -r requirements.txt
  only:
    - main

run_app:
  stage: run_app
  script:
    - source myenv/bin/activate  # Activate the virtual environment
    - python app.py -i urls.json
  only:
    - main

push_output:
  stage: push_output
  script:
    - git checkout -b output  # Create or switch to the 'output' branch
    - git add .  # Add all changes (output files)
    - git commit -m "Update output"  # Commit the changes
    - git push origin output  # Push changes to the 'output' branch
  only:
    - main

